version: '3'

services:
  api:
    container_name: Stock_Project_api
    build: .
    restart: always
    ports:
      - 3009:3009
    working_dir: /app
    volumes:
      - ./src:/app/src
    command: dev
    env_file:
      - .env
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - database
  database:
    container_name: stock_project_db
    image: mongo:4
    restart: always
    ports:
      - 27017:27017